export const index = (axios, params) => axios.get('/admin/diet', { params }).then(_ => _.data)
export const indexWeb = (axios) => axios.get('/api/diet').then(_ => _.data)
export const show = (axios,id) => axios.get(`/admin/diet/${id}`).then(_ => _.data)
export const update = (axios,id,data) => axios.put(`/admin/diet/${id}`,data)
export const create = (axios,data) => axios.post('/admin/diet',data)